### ISSUE TITLE
PowerShell failed at stage of "Installing Active Directory ..."

### ISSUE THREAD

**Issue by Li-Yanzhi** [billcurtis/AzSHCISandbox#9]
In Azure VM , when executing **New-AzSCHCISandbox.ps1**,  it will throw exception at stage of "**Installing Active Directory ...**", I have tried several times even with higher memory for MgmtVM (32GB) and DC VM (4GB) and got same error. 

The error was thrown from line "`Install-ADDSForest  @params -InstallDns -Confirm -Force -NoRebootOnCompletion`" of function `New-DCVM`,  why this cmdlet will not wait for operation to complete.

```
...
VERBOSE: Configuring NIC Settings for Domain Controller
VERBOSE: Configuring Trusted Hosts
VERBOSE: Installing Active Directory Forest. This will take some time...
VERBOSE: Installing Active Directory...
The server did not respond with an encrypted session key within the specified time-out period.
At D:\hcilab\AzSHCISandbox\New-AzSHCISandbox.ps1:1359 char:5
+     Invoke-Command -VMName AzSMGMT -Credential $domainCred -ScriptBlo ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (dc:String) [], PSRemotingDataStructureException
    + FullyQualifiedErrorId : PSSessionStateBroken
    + PSComputerName        : AzSMGM

```

**Comment by billcurtis** [comment]
Haven't seen this particular error before.  What are:

1. The disks you are using in your Hyper-V Host?
2. Hyper-V Version?
3. PowerShell version?
